name: Deploy get conversation Lambda

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-1
  GO_DIRECTORY: lambda/cmd/get_conversation
  S3_BUCKET: bedrock-app-lambda-code-bucket
  S3_KEY: get_conversation.zip
  LAMBDA_FUNCTION: get_conversation

jobs:
  lambda_deploy:
    environment: deploy_lambda
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache: true
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Go build
        run: |
          cd ${{ env.GO_DIRECTORY }}
          GOOS=linux GOARCH=arm64 go build -o bootstrap main.go
          chmod +x bootstrap
          zip ${{ env.S3_KEY }} bootstrap
      - name: Upload to S3
        run: |
          aws s3 cp ${{ env.GO_DIRECTORY }}/${{ env.S3_KEY }} s3://${{ env.S3_BUCKET }}/${{ env.S3_KEY }}
      # - name: Deploy lambda
      #   run: |
      #     aws lambda update-function-code --function-name ${{ env.LAMBDA_FUNCTION }} --s3-bucket ${{ env.S3_BUCKET }} --s3-key ${{ env.S3_KEY }}